alias: "[Alarm] Active Nut When nut home"
description: "Active input_boolean.nelly_active quand l'objet Nut revient à la maison (mode Alarme)."
triggers:
  - trigger: state
    entity_id:
      - device_tracker.nut_rose_presence
    from: not_home
    to: home
conditions:
  - condition: state
    entity_id: input_select.modes_maison
    state: Alarme
  - condition: state
    entity_id: device_tracker.nut_rose_presence
    state: home
  - condition: state
    entity_id: input_boolean.nelly_active
    state: "off"
actions:
  - action: input_boolean.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.nelly_active
mode: single
