alias: "[Vacuum] Ask Start Alarm On"
description: "Envoie une notification pour demander si l'on souhaite annuler le lancement de l'aspirateur lorsque le mode de la maison passe en Alarme, que l'aspirateur est sur son dock et que personne n'est à la maison."
mode: restart
triggers:
  - entity_id:
      - input_select.modes_maison
    to: Alarme
    trigger: state
conditions:
  - condition: state
    entity_id: vacuum.dreamebot_d10_plus
    state: docked
  - condition: state
    entity_id: group.persons
    state: not_home
actions:
  - variables:
      last_person_left: >-
        {% set ns = namespace(name='guillaume', ts=0) %}
        {% for person_name in ['guillaume', 'nelly', 'oscar'] %}
          {% set person_entity = 'person.' ~ person_name %}
          {% set person_state = states('person.' ~ person_name) %}
          {% set person_ts = as_timestamp(states[person_entity].last_changed, 0) %}
          {% if person_state == 'not_home' and person_ts >= ns.ts %}
            {% set ns.name = person_name %}
            {% set ns.ts = person_ts %}
          {% endif %}
        {% endfor %}
        {{ ns.name }}
      ask_targets: >-
        {% if last_person_left == 'guillaume' %}
          guillaume
        {% else %}
          guillaume;{{ last_person_left }}
        {% endif %}
  - alias: Je vais lancer l'aspirateur dans 5 minutes ? Voulez-vous l'annuler ?
    action: script.notify_ask_mobile
    data:
      target: "{{ ask_targets }}"
      ask_tag: ask_start_vacuum_alarm_on
      title: "[Aspirateur]"
      message: Je vais lancer l'aspirateur dans 5 minutes ? Voulez-vous l'annuler ?
      icon: mdi:robot-vacuum-alert
      channel: presence
      yes_title: "Oui"
      no_title: "Non"
      timeout: 300
    response_variable: ask_result
  - condition: state
    entity_id: group.persons
    state: not_home
  - if:
      - condition: template
        value_template: "{{ ask_result.answer not in ['timeout', 'invalid_target'] }}"
        alias: Ask Result != Timeout
    then:
      - if:
          - condition: template
            value_template: "{{ ask_result.answer == 'yes' }}"
            alias: Cancel Vaccum
        then:
          - action: script.notify_send_notifications
            data:
              target: "{{ ask_targets }}"
              title: "[Aspirateur]"
              message: Ok, je ne lance pas l'aspirateur.
              icon: mdi:robot-vacuum-off
              channel: presence
        else:
          - action: script.notify_send_notifications
            data:
              target: "{{ ask_targets }}"
              title: "[Aspirateur]"
              message: Ok, je lance l'aspirateur.
              icon: mdi:robot-vacuum
              channel: presence
          - data: {}
            target:
              entity_id:
                - vacuum.dreamebot_d10_plus
            alias: Start DreameBot D10 Plus
            action: vacuum.start
    else:
      - action: script.notify_send_notifications
        data:
          target: "{{ ask_targets }}"
          title: "[Aspirateur]"
          message: Sans réponse, je lance l'aspirateur.
          icon: mdi:robot-vacuum
          channel: presence
      - data: {}
        target:
          entity_id:
            - vacuum.dreamebot_d10_plus
        alias: Start DreameBot D10 Plus
        action: vacuum.start
