alias: "[Confort] Fenêtres - Suivi du minimum de température"
description: Met à jour le minimum atteint depuis l'ouverture des fenêtres.
triggers:
  - trigger: state
    entity_id: sensor.temperatures_maison
  - trigger: state
    entity_id:
      - binary_sensor.fenetres_maison
    for:
      hours: 0
      minutes: 0
      seconds: 10
conditions:
  - condition: state
    entity_id: input_boolean.aeration_active
    state:
      - "on"
actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.fenetres_maison
            state: "on"
          - condition: template
            value_template: >-
              {{ states('sensor.temperatures_maison') | float(99)<=
              states('input_number.temp_min_aeration') | float(99) }}
        sequence:
          - action: input_number.set_value
            target:
              entity_id: input_number.temp_min_aeration
            data:
              value: >-

                {{ ((states('sensor.temperatures_maison') | float(0) * 10) | int
                / 10) }}
      - conditions:
          - condition: state
            entity_id: binary_sensor.fenetres_maison
            state: "off"
        sequence:
          - action: input_boolean.turn_off
            target:
              entity_id: input_boolean.aeration_active
mode: single
max_exceeded: silent
