alias: "[Confort] Fenêtres - Mémorisation température ouverture"
description: >-
  Enregistre la température maison à la première ouverture de fenêtre.
  Initialise aussi le minimum de suivi de tendance.
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.magnet_eliott_contact
      - binary_sensor.magnet_oscar_contact
      - binary_sensor.magnet_parents_contact
      - binary_sensor.magnet_living_room_left_contact
      - binary_sensor.magnet_living_room_right_contact
    to:
      - "on"
    for:
      hours: 0
      minutes: 0
      seconds: 30
conditions:
  - condition: state
    entity_id: input_boolean.aeration_active
    state:
      - "off"
  - condition: template
    value_template: |-
      {{ (now() -
            states.input_number.temp_reference_aeration.last_updated).total_seconds()
            > 18000 }}
    alias: Dernière température de référence > 5h
actions:
  - action: input_boolean.turn_on
    target:
      entity_id: input_boolean.aeration_active
    data: {}
    alias: "Activer :"
  - action: input_number.set_value
    target:
      entity_id: input_number.temp_reference_aeration
    data:
      value: "{{ states('sensor.temperatures_maison') | float(0) | round(1) }}"
    alias: "Mise à jour : "
  - action: input_number.set_value
    target:
      entity_id: input_number.humid_reference_aeration
    data:
      value: "{{ states('sensor.humidite_maison') | float(0) | round(1) }}"
    alias: "Mise à jour : "
  - action: input_number.set_value
    target:
      entity_id: input_number.temp_min_aeration
    data:
      value: >-
        {{ ((states('sensor.temperatures_maison') | float(0) * 10) | int) / 10
        }}
    alias: "Mise à jour : "
  - action: input_number.set_value
    target:
      entity_id: input_number.humid_min_aeration
    data:
      value: "{{ ((states('sensor.humidite_maison') | float(0) * 10) | int) / 10 }}"
    alias: "Mise à jour : "
mode: single
max_exceeded: silent
