alias: "[Lights] Chambre Parents"
description: "Gère l'éclairage et l'ouverture des volets de la chambre parents selon présence et mode."
mode: restart
triggers:
  - entity_id:
      - binary_sensor.motion_parents_occupancy
      - input_boolean.mode_auto_parents
    to: "on"
    trigger: state
conditions:
  - condition: state
    entity_id: input_boolean.mode_auto_parents
    state: "on"
  - condition: state
    entity_id: binary_sensor.motion_parents_occupancy
    state: "on"
actions:
  - data: {}
    target:
      entity_id:
        - light.mibedsidelamp2
        - light.yeelight_bslamp1
    alias: Turn on Chevets
    action: light.turn_on
  - if:
      - condition: state
        entity_id: input_select.modes_maison
        state: Journée
    then:
      - if:
          - condition: template
            value_template: "{{ is_state('sun.sun', 'below_horizon')}}"
            alias: Sun Down
        then:
          - data:
              position: 25
            target:
              entity_id: cover.volets_parents_state
            alias: Volets Parents 25%
            action: cover.set_cover_position
        else:
          - data:
              position: 100
            target:
              entity_id: cover.volets_parents_state
            alias: Volets Parents 100%
            action: cover.set_cover_position
        alias: Open Volets
    alias: Modes Maison is 'Journée'
  - if:
      - condition: template
        value_template: "{{ not is_state('input_select.modes_maison', 'Nuit') }}"
        alias: Not 'Nuit'
    then:
      - data: {}
        alias: Turn on Plafonnier
        target:
          entity_id:
            - light.light_parents
        action: light.turn_on
    alias: " Not 'Nuit' Turn on Plafonnier"
  - wait_template: "{{ is_state('binary_sensor.motion_parents_occupancy', 'off') }}"
    continue_on_timeout: false
  - delay:
      hours: 0
      minutes: "{{ states('input_number.now_light_delay_off')|int}}"
      seconds: 0
      milliseconds: 0
    alias: Wait the number of seconds that has been set
  - if:
      - condition: state
        entity_id: input_boolean.mode_auto_parents
        state: "on"
    then:
      - alias: Turn off the light
        data: {}
        target:
          entity_id:
            - light.mibedsidelamp2
            - light.light_parents
            - light.yeelight_bslamp1
        action: light.turn_off
