alias: "[Lights] Extérieur"
description: "Allume/éteint les lumières extérieures selon mouvements, contacts et mode."
triggers:
  - entity_id:
      - binary_sensor.motion_outside_occupancy
      - binary_sensor.magnet_living_room_left_contact
      - binary_sensor.magnet_living_room_right_contact
    from: "off"
    to: "on"
    trigger: state
  - entity_id:
      - input_boolean.mode_auto_exterieur
    trigger: state
conditions:
  - condition: state
    entity_id: input_boolean.mode_auto_exterieur
    state: "on"
  - condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.motion_outside_occupancy
        state: "on"
      - condition: state
        entity_id: binary_sensor.magnet_living_room_left_contact
        state: "on"
      - condition: state
        entity_id: binary_sensor.magnet_living_room_right_contact
        state: "on"
    alias: "Motion or open "
actions:
  - if:
      - condition: not
        conditions:
          - condition: state
            entity_id: input_select.modes_maison
            state: Nuit
          - condition: state
            entity_id: input_select.modes_maison
            state: Soirée TV
          - condition: state
            entity_id: binary_sensor.freebox_player_pop_state
            state: "on"
      - condition: state
        entity_id: input_boolean.volets_salon_auto
        state: "on"
    then:
      - data: {}
        target:
          entity_id: cover.volets_salon_state
        alias: Open Volets Salon
        action: cover.open_cover
    enabled: true
  - if:
      - condition: template
        value_template: "{{ is_state('sun.sun', 'below_horizon') }}"
        alias: Sun down
    then:
      - if:
          - condition: time
            before: input_datetime.evening_start_week_end
            after: input_datetime.school_end_today
          - condition: state
            entity_id: light.yeelight_stripe_local
            state: "off"
        then:
          - target:
              entity_id:
                - switch.ikea_tradfri_control_outlet
            data: {}
            action: switch.turn_on
        enabled: false
        alias: Guirlandes (Changer prise)
      - data:
          color_temp_kelvin: "{{ states('input_number.now_light_temp_salon') | int }}"
          brightness_pct: 100
        alias: Turn on the light
        target:
          entity_id:
            - light.yeelight_stripe_local
        action: light.turn_on
  - wait_template: "{{ is_state('binary_sensor.motion_outsidd_occupancy', 'on') }}"
    continue_on_timeout: true
    timeout: 60
    alias: Wait motion Outside Or 1 minute
  - wait_template: "{{ is_state('binary_sensor.motion_outsidd_occupancy', 'off') }}"
    continue_on_timeout: true
    alias: Wait no motion Outside
    timeout: 300
  - delay:
      hours: 0
      minutes: "{{ states('input_number.now_light_delay_off')|int}}"
      seconds: 0
      milliseconds: 0
    alias: Wait the number of seconds that has been set
  - alias: Turn off the light
    target:
      entity_id:
        - light.yeelight_stripe_local
    data: {}
    action: light.turn_off
mode: restart
