alias: "[Lights] Salon"
description: "Gère l'éclairage du salon selon présence, luminosité et mode."
triggers:
  - entity_id:
      - binary_sensor.motion_living_room_occupancy
      - binary_sensor.magnet_living_room_left_contact
      - binary_sensor.magnet_living_room_right_contact
      - input_boolean.mode_auto_salon
    to: "on"
    trigger: state
conditions:
  - condition: state
    entity_id: input_boolean.mode_auto_salon
    state: "on"
    enabled: true
  - condition: state
    entity_id: binary_sensor.motion_living_room_occupancy
    state:
      - "on"
actions:
  - alias: "Not Soirée TV  turn on lights "
    if:
      - condition: template
        value_template: "{{ not is_state('input_select.modes_maison', 'Soirée TV') }}"
        alias: Not 'Soirée TV'
      - condition: numeric_state
        entity_id: sensor.living_room_illuminance_old
        below: input_number.luminosite_min
        enabled: true
    then:
      - alias: Turn on Bibliothèque & Sapin
        data: {}
        target:
          entity_id:
            - light.ikea_tradfri_e27_1055lm_2
            - light.sapin_local
        action: light.turn_on
      - alias: " Not 'Nuit' Turn on Plafonnier"
        if:
          - condition: template
            value_template: "{{ not is_state('input_select.modes_maison', 'Nuit') }}"
            alias: Not 'Nuit'
        then:
          - data: {}
            alias: Turn on Plafonnier
            target:
              entity_id: light.enki_lexman_e27_led_white_bulb_living_room
            action: light.turn_on
  - if:
      - condition: or
        conditions:
          - condition: state
            entity_id: input_select.modes_maison
            state: Soir
          - condition: state
            entity_id: input_select.modes_maison
            state: Soirée TV
    then:
      - data: {}
        target:
          entity_id: input_boolean.mode_auto_salon
        action: input_boolean.turn_off
      - stop: Mode Auto Salon OFF
    alias: Mode soir ou soirée TV mode auto cuisine off
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
    alias: Wait 5sec (motion if window opened)
  - wait_template: "{{ is_state('binary_sensor.motion_living_room_occupancy', 'off')
      }}"
    continue_on_timeout: false
  - delay:
      hours: 0
      minutes: "{{ states('input_number.now_light_delay_off')|int}}"
      seconds: 0
      milliseconds: 0
    alias: Wait the number of seconds that has been set
  - alias: Turn off the light
    if:
      - condition: state
        entity_id: input_boolean.mode_auto_salon
        state: "on"
    then:
      - alias: Turn off the light
        data: {}
        target:
          entity_id:
            - light.ikea_tradfri_e27_1055lm_2
            - light.enki_lexman_e27_led_white_bulb_living_room
            - light.sapin_local
        action: light.turn_off
mode: restart
