alias: "[Presence] Sync Oscar Keys From Phone"
description: "Force les clés d'Oscar à absent quand son téléphone est absent en GPS et en Wi-Fi."
mode: single
triggers:
  - trigger: state
    entity_id:
      - device_tracker.samsung_e10
      - device_tracker.a55_de_oscar
    to: "not_home"
    for:
      minutes: 5
conditions:
  - condition: state
    entity_id: device_tracker.samsung_e10
    state: "not_home"
  - condition: state
    entity_id: device_tracker.a55_de_oscar
    state: "not_home"
  - condition: template
    value_template: "{{ states('device_tracker.nut_vert_presence') != 'not_home' }}"
actions:
  - action: button.press
    target:
      entity_id: button.change_presence_nut_oscar
