alias: "[Presence] Sync Oscar Keys From Phone"
description: >-
  Désactive oscar_active quand le téléphone d'Oscar est absent en GPS et en
  Wi-Fi.
triggers:
  - trigger: state
    entity_id:
      - device_tracker.a55_de_oscar
      - device_tracker.nmap_tracker_1a_d6_c6_43_dc_ff
      - device_tracker.samsung_a55
    to: not_home
    for:
      minutes: 5
conditions:
  - condition: state
    entity_id: device_tracker.a55_de_oscar
    state: not_home
  - condition: state
    entity_id: device_tracker.nmap_tracker_1a_d6_c6_43_dc_ff
    state: not_home
  - condition: not
    conditions:
      - condition: state
        entity_id: device_tracker.samsung_a55
        state:
          - home
actions:
  - action: input_boolean.turn_off
    target:
      entity_id: input_boolean.oscar_active
  - condition: state
    state:
      - home
    entity_id: device_tracker.nut_vert_presence
  - action: button.press
    metadata: {}
    target:
      entity_id: button.change_presence_nut_oscar
    data: {}
mode: single
