alias: "[Budget] N8N Budget hebdomadaire"
description: "Reçoit via webhook n8n le résumé hebdomadaire des dépenses et revenus, crée une notification persistante et diffuse (optionnellement) le message en TTS ou SMS."
triggers:
  - trigger: webhook
    allowed_methods:
      - POST
      - PUT
    local_only: false
    webhook_id: REMOVED
conditions: []
actions:
  - action: rest_command.radio_home
    data: {}
    response_variable: response_variable
  - action: notify.persistent_notification
    metadata: {}
    data:
      title: "[TTS] Radio Home"
      message: "{{ response_variable.content }}"
  - alias: Script TTS toutes_les_pieces
    data:
      media_player: media_player.google_home_parents
      message: |
        {{ response_variable.content }}.
    action: script.tts_send_tts
    enabled: false
  - alias: Message SMS
    data:
      action: sendSms
      number: TELEPHONE_SUPPRIME
      message: "{{ response_variable.content }}"
    action: script.mqtt_send_topics
    enabled: true
mode: single
