alias: "[TTS] School Start & End"
description: Play TTS reminders for school start and end times
triggers:
  - entity_id:
      - input_boolean.bouton_test
    trigger: state
    id: start
  - value_template: >-
      {{ (now().timestamp() | timestamp_custom('%H:%M')) ==
      (today_at(states('input_datetime.school_start_today')) -
      timedelta(minutes=10)).strftime('%H:%M') }}
    alias: 10 Minutes Before School Start
    id: start
    trigger: template
  - value_template: >-
      {{ (now().timestamp() | timestamp_custom('%H:%M')) ==
      (today_at(states('input_datetime.school_start_today')) -
      timedelta(minutes=5)).strftime('%H:%M') }}
    alias: 5 Minutes Before School Start
    id: start
    trigger: template
  - value_template: >-
      {{ (now().timestamp() | timestamp_custom('%H:%M')) ==

      (strptime(states('input_datetime.school_start_today'), '%H:%M:%S') -
      strptime(states('input_datetime.school_start_timer'),
      '%H:%M:%S')).total_seconds() | timestamp_custom('%H:%M', false) }}
    alias: Timer (15 minutes) Before School Start
    id: start
    trigger: template
  - value_template: >-
      {{ (now().timestamp() | timestamp_custom('%H:%M')) ==
      (today_at(states('input_datetime.school_end_today')) -
      timedelta(minutes=10)).strftime('%H:%M') }}
    alias: 10 Minutes Before School End
    id: end_10min
    trigger: template
  - value_template: >-
      {{ (now().timestamp() | timestamp_custom('%H:%M')) ==
      (today_at(states('input_datetime.school_end_today')) -
      timedelta(minutes=5)).strftime('%H:%M') }}
    alias: 5 Minutes Before School End
    id: end_5min
    trigger: template
  - value_template: >-
      {{ (now().timestamp() | timestamp_custom('%H:%M')) ==

      (strptime(states('input_datetime.school_end_today'), '%H:%M:%S') -
      strptime(states('input_datetime.school_end_timer'),
      '%H:%M:%S')).total_seconds() | timestamp_custom('%H:%M', false) }}
    alias: Timer (0 minutes) Before School End
    id: end_timer
    trigger: template
conditions:
  - condition: state
    entity_id: input_boolean.school
    state: "on"
  - condition: state
    entity_id: group.persons
    state: home
actions:
  - variables:
      time: "{{ now().strftime('%H:%M') }}"
      sncf: "{{ trigger.id == 'start' }}"
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'start' }}"
        sequence:
          - action: script.facts_fun_fact_aleatoire
            data: {}
            response_variable: fact_result
          - variables:
              message: "{{ fact_result.fun_fact }}"
      - conditions:
          - condition: template
            value_template: "{{ trigger.id in ['end_5min', 'end_10min', 'end_timer'] }}"
        sequence:
          - variables:
              message: |-
                {% set end_messages = {
                  'end_10min': "Prépare-toi à partir chercher Eliott.",
                  'end_5min':  "Il faut partir maintenant pour être à l'heure.",
                  'end_timer': "Il faut aller chercher Eliott tout de suite."
                } %} {{ end_messages[trigger.id] }}
    default:
      - variables:
          message: C'est l'heure pour Eliott.
  - alias: Send TTS message
    action: script.tts_send_tts
    data:
      media_player: media_player.ni_oscar_ni_parents
      message: Il est {{ time }}. {{ message }}
      sncf: "{{ sncf }}"
mode: single
